language: cpp

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_script:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - cmake ..

script: make # && make test
